cuda_compiler_version:                            # [linux and x86_64]
  - None                                          # [linux and x86_64]
cudnn:                                            # [linux and x86_64]
  - undefined                                     # [linux and x86_64]