{% set version = "2.4.0" %}

package:
  name: ray-packages
  version: {{ version }}

source:
  url: https://github.com/ray-project/ray/archive/ray-{{ version }}.tar.gz
  sha256: b0110a84630b2f6d10cd13e8ac955875c3658373eb6cabcc77cf316de3c28066
  patches:
    # - patches/0001-Redis-deps-now-build-but-do-not-link.patch  # [not osx]
    - patches/0002-Disable-making-non-core-entry-scripts.patch
  #   - patches/0003-Remove-all-dependencies-from-setup.py.patch
  #   - patches/0004-Ignore-warnings-in-event.cc-and-logging.cc.patch
  #   - patches/0005-Add-bazel-linkopts-libs.patch
    - patches/0006-flexible-bazel-version.patch
    # https://github.com/ray-project/ray/pull/34151
    - patches/0007-fix-namespace-errors.patch
    # https://github.com/ray-project/ray/issues/8902
    - patches/0008-fix-out-of-memory-errors.patch


build:
  number: 0
  # py36 is technically supported but we don't want to build for it
  skip: true  # [py<38]
  # skipping architectures that do not yet have bazel
  skip: true  # [(linux and (s390x or ppc64le))]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch          # [not win]
    - m2-patch       # [win]

outputs:
  - name: ray-all
    build:
      # Misssing ray-data on 3.11, ray-serve and ray-k8s for all
      skip: true
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-air', exact=True) }}
        # cannot pin exactly due to ray-dashboard being built
        # for different nodejs versions in the same CI job
        - ray-dashboard =={{ version }}=*_{{ PKG_BUILDNUM }}
        - {{ pin_subpackage('ray-default', exact=True) }}
        - {{ pin_subpackage('ray-k8s', exact=True) }}
        - {{ pin_subpackage('ray-data', exact=True) }}
        - {{ pin_subpackage('ray-rllib', exact=True) }}
        - {{ pin_subpackage('ray-serve', exact=True) }}
        - {{ pin_subpackage('ray-train', exact=True) }}
        - {{ pin_subpackage('ray-tune', exact=True) }}
    test:
      imports:
        # dummy test; actual tests are in subpackages
        - ray

  - name: ray-core
    script: build-core.sh  # [not win]
    script: build-core.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - bazel =5.2.0
        - sysroot_linux-64 2.17  # [linux64]
        - patchelf  # [linux]
        - curl
        - cython >=0.29.32
        - make  # [not win]
        - m2-make  # [win]
        - m2-bash  # [win]
        - python
        - git  # [not win]
        - pkg-config  # [osx or (linux and aarch64)]
      host:
        - python
        - pip
        - packaging
        - openjdk =11
      run:
        - python
        - aiosignal
        - attrs
        - click >=7.0,<=8.0.4
        - colorama
        - filelock
        - frozenlist
        - grpcio >=1.42,<1.49
        - jsonschema
        - msgpack-python >=1.0.0,<2.0.0
        - numpy >=1.20
        - packaging  # [py>=310]
        - protobuf >=3.15.3,!=3.19.5,<4.0.0
        - psutil
        - pyyaml
        - requests
        - setproctitle==1.2.2
        - virtualenv
        - setuptools # pkg_resources

    test:
      imports:
        - ray
        - ray._raylet
        - ray.actor
        - ray.runtime_context
        - ray._private.state
        - ray._private.worker
      commands:
        - python -c "import ray; ray.init(include_dashboard=False)"

  # the various ray[extra] installs, alphabetically
  - name: ray-air
    build:
      # Misssing ray-data on 3.11
      skip: true  # [py>310]
      # Missing ray-serve
      skip: true
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-data', exact=True) }}
        - {{ pin_subpackage('ray-serve', exact=True) }}
        - {{ pin_subpackage('ray-train', exact=True) }}
        - {{ pin_subpackage('ray-tune', exact=True) }}
    test:
      imports:
        - ray.air

  - name: ray-dashboard
    build:
      script:
        - cd python/ray/dashboard/client
        - npm install
        - npm ci
        - npm run build
        # not sure why this seems to get copied on windows but not linux...
        - mkdir -p $SP_DIR/ray/dashboard/client             # [not win]
        - cp -R ./build $SP_DIR/ray/dashboard/client/build  # [not win]
    requirements:
      build:
        - nodejs <18
      host: #TODO: Determine if upstream has node version rec, vs 18 fails with regex error in webpack
        - nodejs <18 
        - python
      run:
        - python
        - {{ pin_subpackage('ray-core', exact=True) }}
        - typing-extensions
        - setuptools # pkg_resources
    test:
      imports:
        - ray.dashboard
      commands:
        - python -c "import ray; ray.init(include_dashboard=True)"

  - name: ray-data
    # https://github.com/ray-project/ray/issues/33232
    build:  
      skip: true  # [py>310]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-core', exact=True) }}
        - numpy >=1.20
        - pandas >=1.3
        - pyarrow >=6.0.1
        - fsspec
        - setuptools # pkg_resources
    test:
      imports:
        - ray.data

  - name: ray-default
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-core', exact=True) }}
        # cannot pin exactly due to ray-dashboard being built
        # for different nodejs versions in the same CI job
        - ray-dashboard =={{ version }}=*_{{ PKG_BUILDNUM }}
        - aiohttp >=3.7
        - aiohttp-cors
        - colorful
        # TODO
        # - gpustat >=1.0.0
        - gpustat
        - opencensus
        - prometheus_client >=0.7.1
        - pydantic
        - requests
        - smart_open
        - py-spy >=0.2.0
        - setuptools # pkg_resources

    test:
      imports:
        # ray-default is a convenience wrapper with no imports of its own
        - ray
        # init-code seemingly depends on platform or other ambient things;
        # the following doesn't get triggered in CI, but was a problem in
        # https://github.com/conda-forge/ray-packages-feedstock/issues/16
        - ray._private.metrics_agent

  - name: ray-k8s
    build:
      # missing kubernetes
      skip: true
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-core', exact=True) }}
        - kubernetes
        - urllib3
    test:
      imports:
        # there doesn't appear to be a k8s module, not sure how to test this
        - ray

  - name: ray-rllib
    build:
      # 3.11 is missing ray-tune
      skip: true  # [py>310]
      entry_points:
        - rllib = ray.rllib.scripts:cli
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-tune', exact=True) }}
        - dm-tree
        - gymnasium ==0.26.3
        - lz4
        - matplotlib-base !=3.4.3
        - pyyaml
        - scikit-image
        - scipy
        - typer
        - rich
    test:
      imports:
        - ray.rllib
      commands:
        # some interaction with rich and the test runner in azure
        # xref https://github.com/Textualize/rich/issues/2411 ?
        - python -c "import subprocess, os; os.environ['PYTHONIOENCODING']='utf-8'; subprocess.run(['rllib', '--help'], capture_output=True, check=True)"

  - name: ray-serve
    build:
      # missing starlette, fastapi
      skip: true
      entry_points:
        - serve = ray.serve.scripts:cli
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-default', exact=True) }}
        - uvicorn
        - requests
        - starlette
        - fastapi
        - aiorwlock
    test:
      imports:
        - ray.serve

  - name: ray-tune
    build:
      # Not yet compatible with 3.11
      skip: true  # [py>310]
      entry_points:
        - tune = ray.tune.scripts:cli
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-default', exact=True) }}
        - pandas
        - requests
        - tabulate
        - tensorboardX >=1.9
    test:
      imports:
        - ray.tune

  - name: ray-train
    build:
      # 3.11 is missing ray-tune
      skip: true  # [py>310]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-tune', exact=True) }}
    test:
      imports:
        - ray.train

about:
  home: https://www.ray.io/
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - licenses/abseil-LICENSE.txt
    - licenses/antirez-redis-COPYING.txt
    - licenses/arrow-LICENSE.txt
    - licenses/boost-LICENSE_1_0.txt
    - licenses/boringssl-LICENSE.txt
    - licenses/deckarep-golang-set-LICENSE.txt
    - licenses/flatbuffers-LICENSE.txt
    - licenses/gabime-spdlog-LICENSE.txt
    - licenses/gflags-COPYING.txt
    - licenses/glog-COPYING.txt
    - licenses/go-logr-LICENSE.txt
    - licenses/googletest-LICENSE.txt
    - licenses/grpc-LICENSE.txt
    - licenses/msgpack-COPYING.txt
    - licenses/onsi-ginkgo-LICENSE.txt
    - licenses/onsi-gomega-LICENSE.txt
    - licenses/opencensus-LICENSE.txt
    - licenses/opencensus-proto-LICENSE.txt
    - licenses/prometheus-LICENSE.txt
    - licenses/redis-hiredis-COPYING.txt
    - licenses/tporadowski-redis-license.txt
    - licenses/zlib-LICENSE.txt
  summary: Ray is a fast and simple framework for building and running distributed applications.
  description: |
    Ray is a fast and simple framework for building and running
    distributed applications. It is split into ray-core, ray-default,
    ray-dashboard, ray-serve, ray-rllib, ray-k8s, ray-data, ray-tune,
    ray-train, ray-air and ray-all packages.
  doc_url: https://docs.ray.io
  dev_url: https://github.com/ray-project/ray

extra:
  recipe-maintainers:
    - dHannasch
    - h-vetinari
    - vnlitvinov
    - krfricke
    - mattip
