{% set version = "2.3.0" %}

package:
  name: ray-packages
  version: {{ version }}

source:
  url: https://github.com/ray-project/ray/archive/ray-{{ version }}.tar.gz
  sha256: 0554b8711db70fae4c0acc8e01674901a84b81405f5247ed933b12ed047ff353
  patches:
    - patches/0004-Disable-making-non-core-entry-scripts.patch
    - patches/0010-Remove-all-dependencies-from-setup.py.patch
    - patches/0011-Ignore-warnings-in-event.cc-and-logging.cc.patch
    - patches/0013-Add-bazel-linkopts-libs.patch
    # https://github.com/ray-project/ray/pull/34151
    - patches/0014-fix-namespaces.patch
    - patches/0015-use-newer-dependencies.patch

build:
  number: 0
  # Skipping architectures that do not yet have bazel, so only build for linux64, linux-aarch64 and win64.
  skip: True  # [(linux and (s390x or ppc64le))]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch          # [not win]
    - m2-patch       # [win]
    # We use an older bazel version because the newer series (v6+) introduce a feature
    # that is incompatible with the ray bazel rules.
    - bazel 5.4.1
    - curl
    - git         # [not win]
    - m2-make     # [win]
    - make        # [not win]
    - patchelf    # [linux]
    - python  
    - sysroot_linux-64 2.17  # [linux and x86_64]
  host:
    - python
    - pip
    - packaging
    - setuptools
    - wheel
    - cython 0.29.32
    - pkg-config  # [osx or (linux and aarch64)]

outputs:
  - name: ray-all
    build:
      # Until all of the ray-* packages are available in defaults, skipping the ray-all metapackage.
      skip: True
    requirements:
      host:
      run:
        - python
        - {{ pin_subpackage('ray-default', exact=True) }}
    test:
      imports:
        # dummy test; actual tests are in subpackages
        - ray

  - name: ray-core
    script: build-core.sh   # [not win]
    script: build-core.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - patch          # [not win]
        - m2-patch       # [win]
        - bazel 5.4.1
        - curl
        - git            # [not win]
        - m2-make        # [win]
        - make           # [not win]
        - python  
        - sysroot_linux-64 2.17  # [linux and x86_64]
      host:
        - python
        - openjdk 11
        - pip
        - packaging
        - pkg-config     # [osx or (linux and aarch64)]
        - setuptools
        - wheel
        - cython 0.29.32
      run:
        - python
        - aiosignal
        - attrs
        - click >=7.0,<=8.0.4
        - colorama
        - filelock
        - frozenlist
        - grpcio >=1.42,<1.49
        - jsonschema
        - msgpack-python >=1.0.0,<2.0.0
        - numpy >=1.20
        - packaging
        - protobuf >=3.15.3,!=3.19.5,<4.0.0
        - psutil
        - pyyaml
        - requests
        - setproctitle =1.2.2
        - virtualenv >=20.0.24

    test:
      imports:
        - ray
        - ray._raylet
        - ray.actor
        - ray.runtime_context
        - ray._private.state
        - ray._private.worker
      commands:
        - python -c "import ray; ray.init(include_dashboard=False)"

  - name: ray-default
    build:
      skip: True
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-core', exact=True) }}
        - aiohttp >=3.7
        - aiohttp-cors
        - colorful
        # gpustat has a dependency which does not exist on Windows;
        # skip it there until gpustat is fixed as it is optional.
        - gpustat  # [not win]
        - opencensus
        - prometheus_client >=0.7.1,<0.14.0
        - pydantic
        - jsonschema
        - requests
        - smart_open
        - py-spy >=0.2.0

    test:
      imports:
        # ray-default is a convenience wrapper with no imports of its own
        - ray
        # init-code seemingly depends on platform or other ambient things;
        # the following doesn't get triggered in CI, but was a problem in
        # https://github.com/conda-forge/ray-packages-feedstock/issues/16
        - ray._private.metrics_agent

about:
  home: https://www.ray.io/
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - licenses/abseil-LICENSE.txt
    - licenses/antirez-redis-COPYING.txt
    - licenses/arrow-LICENSE.txt
    - licenses/boost-LICENSE_1_0.txt
    - licenses/boringssl-LICENSE.txt
    - licenses/deckarep-golang-set-LICENSE.txt
    - licenses/flatbuffers-LICENSE.txt
    - licenses/gabime-spdlog-LICENSE.txt
    - licenses/gflags-COPYING.txt
    - licenses/glog-COPYING.txt
    - licenses/go-logr-LICENSE.txt
    - licenses/googletest-LICENSE.txt
    - licenses/grpc-LICENSE.txt
    - licenses/msgpack-COPYING.txt
    - licenses/onsi-ginkgo-LICENSE.txt
    - licenses/onsi-gomega-LICENSE.txt
    - licenses/opencensus-LICENSE.txt
    - licenses/opencensus-proto-LICENSE.txt
    - licenses/prometheus-LICENSE.txt
    - licenses/redis-hiredis-COPYING.txt
    - licenses/tporadowski-redis-license.txt
    - licenses/zlib-LICENSE.txt
  summary: Ray is a fast and simple framework for building and running distributed applications.
  description: |
    Ray is a fast and simple framework for building and running
    distributed applications.
  doc_url: https://docs.ray.io/en/latest/
  dev_url: https://github.com/ray-project/ray

extra:
  recipe-maintainers:
    - dHannasch
    - h-vetinari
    - vnlitvinov
    - krfricke
