{% set version = "2.37.0" %}
# launch build
package:
  name: ray-packages
  version: {{ version }}

source:
  url: https://github.com/ray-project/ray/archive/ray-{{ version }}.tar.gz
  sha256: dcf92302ba813080003f33cb874912ee950331f2348822a2b615eb46f9baf0f8
  patches:
    - patches/0001-Redis-deps-now-build-but-do-not-link.patch
    - patches/0002-Disable-making-entry-scripts.patch
    # - patches/0003-Add-bazel-linkopts-libs.patch
    - patches/0004-Ignore-warnings-in-event.cc-and-logging.cc.patch
    - patches/0005-Remove-all-dependencies-from-setup.py.patch
    - patches/0015-Don-t-build-redis-with-jemalloc-on-linux-aarch64.patch  # [linux and aarch64]
    - patches/0016-fix-redis-build-on-macos.patch  # [osx]
    - patches/0017-Don-t-use-Xcode-on-macOS.patch
    - patches/0018-Remove-runtime-agent-dependencies.patch

build:
  number: 0
  skip: true  # [py<39 or py>312]
  skip: true  # [(linux and (s390x or ppc64le))]

# The requirements/build&host sections of ray-core need to be replicated here.
# It is not clear why at this time but not having them here causes conda build to behave non-deterministically and crash. 
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch          # [not win]
    - m2-patch       # [win]
    - bazel =6.5.0
    - curl
    - git  # [not win]
    - m2-make   # [win]
    - make      # [not win]
    - pkg-config  # [osx or (linux and aarch64)]
    - patchelf  # [linux]
    - python  
    - sysroot_linux-64 2.17  # [linux and x86_64]
    - psutil
  host:
    - python
    - pip
    - cython >=0.29.32
    - pkg-config  # [osx]
    - setuptools
    - wheel
    - openjdk =11

outputs:
  - name: ray-all
    build:
      # Until all of the ray-* packages are available in defaults, skipping the ray-all metapackage.
      skip: true
    requirements:
      host:
      run:
        - python
        # Skipped dependencies are commented out, see below for details
        #- {{ pin_subpackage('ray-adag', exact=True) }}
        # autoscaler is completely disabled for now as it's missing a bunch of dependencies
        # and there's not much interest in adding them (yet).
        # autoscaler does not work on Windows, no point of building it; see below
        #- {{ pin_subpackage('ray-autoscaler', exact=True) }}  # [not win]
        - {{ pin_subpackage('ray-client', exact=True) }}
        - {{ pin_subpackage('ray-data', exact=True) }}
        - {{ pin_subpackage('ray-default', exact=True) }}
        - {{ pin_subpackage('ray-dashboard', exact=True) }}
        - {{ pin_subpackage('ray-debug', exact=True) }}
        #- {{ pin_subpackage('ray-observability', exact=True) }}
        - {{ pin_subpackage('ray-rllib', exact=True) }}
        - {{ pin_subpackage('ray-serve', exact=True) }}
        - {{ pin_subpackage('ray-serve-grpc', exact=True) }}
        - {{ pin_subpackage('ray-tune', exact=True) }}
        - {{ pin_subpackage('ray-train', exact=True) }}

    test:
      imports:
        # dummy test; actual tests are in subpackages
        # Skip on osx-arm64 to prevent "Too many open files" error on CI, run tests locally to confirm they pass on OSX
        - ray       # [not (osx and arm64)]

  - name: ray-core
    script: build-core.sh  # [not win]
    script: build-core.bat  # [win]
    build:
      skip: true  # [py<39]
    build:
      entry_points:
        - ray = ray.scripts.scripts:main
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - patch          # [not win]
        - m2-patch       # [win]
        - bazel =6.5.0
        - curl
        - git  # [not win]
        - m2-make   # [win]
        - make      # [not win]
        - pkg-config  # [osx or (linux and aarch64)]
        - patchelf  # [linux]
        - python  
        - sysroot_linux-64 2.17  # [linux and x86_64]
        - psutil
      host:
        - python
        - pip
        - cython >=0.29.32
        - pkg-config  # [osx]
        - setuptools
        - wheel
        - openjdk =11
      run:
        - python
        - click >=7.0
        - filelock
        - jsonschema
        - msgpack-python >=1.0.0,<2.0.0
        - packaging
        - protobuf >=3.15.3,!=3.19.5
        - pyyaml
        - aiosignal
        - frozenlist
        - requests
        # Named "Third-party Install" Upstream
        - psutil
        - setproctitle ==1.2.2
        - colorama
        - aiohttp

    test:
      imports:
        # Skip on osx-arm64 to prevent "Too many open files" error on CI, run tests locally to confirm they pass on OSX
        - ray                           # [not (osx and arm64)]
        - ray._raylet                   # [not (osx and arm64)]
        - ray.actor                     # [not (osx and arm64)]
        - ray.runtime_context           # [not (osx and arm64)]
        - ray._private.state            # [not (osx and arm64)]
        - ray._private.worker           # [not (osx and arm64)]
      commands:
        # 'ray stop' sends a SIGTERM to ray processes to ensure a clean slate
        # Skip on osx to prevent "Too many open files" error on CI, run tests locally to confirm they pass on OSX
        - ray --help                  # [not osx]
        - ray start --head --verbose  # [not osx]
        - ray stop --verbose          # [not osx]
        

  - name: ray-default
    build:
      skip: true  # [py<39]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-core', exact=True) }}
        - aiohttp >=3.7
        - aiohttp-cors
        - colorful
        - grpcio >=1.32.0  # [py<310]
        - grpcio >=1.42.0   # [py>=310]
        - opencensus
        - prometheus_client >=0.7.1
        - py-spy >=0.2.0
        - pydantic !=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,<3
        - requests
        - smart_open
        - virtualenv >=20.0.24,!=20.21.1

    test:
      imports:
      # Skip on osx-arm64 to prevent "Too many open files" error on CI, run tests locally to confirm they pass on OSX
        # ray-default is a convenience wrapper with no imports of its own
        - ray                           # [not (osx and arm64)]
        # init-code seemingly depends on platform or other ambient things;
        # the following doesn't get triggered in CI, but was a problem in
        # https://github.com/conda-forge/ray-packages-feedstock/issues/16
        - ray._private.metrics_agent    # [not (osx and arm64)]

  - name: ray-dashboard
    build:
      script:
        - cd python/ray/dashboard/client
        - npm install
        - npm ci
        - npm run build
        # not sure why this seems to get copied on windows but not linux...
        - mkdir -p $SP_DIR/ray/dashboard/client             # [not win]
        - cp -R ./build $SP_DIR/ray/dashboard/client/build  # [not win]
    requirements:
      host:
        - nodejs
        - python
      run:
        - python
        - {{ pin_subpackage('ray-default', exact=True) }}
        - typing-extensions
        - async-timeout
    test:
      imports:
        - ray.dashboard                                         # [not (osx and arm64)]
      commands:
        # 'ray stop' sends a SIGTERM to ray processes to ensure a clean slate
        # Skip on osx to prevent "Too many open files" error on CI, run tests locally to confirm they pass on OSX
        - ray --help                                            # [not osx]
        - ray start --head --include-dashboard=true --verbose   # [not osx]
        - ray stop --verbose                                    # [not osx]

  - name: ray-debug
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-core', exact=True) }}
        - py-spy >=0.2.0
    test:
      imports:
        # there doesn't appear to be a debug specific module
        - ray                                               # [not (osx and arm64)]

  - name: ray-client
    build:
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-core', exact=True) }}
        - grpcio !=1.56.0  # [osx]
        - grpcio
    test:
      imports:
        # there doesn't appear to be a client module, not sure how to test this
        - ray                                             # [not (osx and arm64)]

  - name: ray-rllib
    build:
      entry_points:
        - rllib = ray.rllib.scripts:cli
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-tune', exact=True) }}
        - dm-tree
        - gymnasium ==0.28.1
        - lz4
        - pyyaml
        - scikit-image
        - scipy
        - typer
        - rich
    test:
      imports:
        - ray.rllib                                       # [not (osx and arm64)]
      commands:
        # some interaction with rich and the test runner in azure
        # xref https://github.com/Textualize/rich/issues/2411 ?
        # Skip on osx-arm64 to prevent "Too many open files" error on CI, run tests locally to confirm they pass on OSX
        - python -c "import subprocess, os; os.environ['PYTHONIOENCODING']='utf-8'; subprocess.run(['rllib', '--help'], capture_output=True, check=True)" # [not (osx and arm64)]

  - name: ray-data
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-core', exact=True) }}
        - numpy >=1.20
        - pandas >=1.3
        - pyarrow >=6.0.1
        - fsspec
    test:
      imports:
        - ray.data                                      # [not (osx and arm64)]

  - name: ray-serve
    build:
      entry_points:
        - serve = ray.serve.scripts:cli
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-default', exact=True) }}
        - requests
        - uvicorn-standard
        - starlette
        - fastapi
        - watchfiles
    test:
      imports:
        - ray.serve                                     # [not (osx and arm64)]

  - name: ray-serve-grpc
    build:
      entry_points:
        - serve = ray.serve.scripts:cli
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-serve', exact=True) }}
        - grpcio >=1.32.0  # [py<310]
        - grpcio >=1.42.0  # [py>=310]
    test:
      imports:
        - ray.serve                                     # [not (osx and arm64)]

  - name: ray-tune
    build:
      entry_points:
        - tune = ray.tune.scripts:cli
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-default', exact=True) }}
        - pandas
        - pyarrow >=6.0.1
        - requests
        - fsspec
        - tensorboardX >=1.9
    test:
      imports:
        - ray.tune                                    # [not (osx and arm64)]

  - name: ray-train
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-tune', exact=True) }}
    test:
      imports:
        - ray.train                                   # [not (osx and arm64)]

  # the various ray[extra] installs, alphabetically
  - name: ray-adag
    build:
      # cupy-cuda12x is not available
      skip: True
    requirements:
      host:
        - python
      run:
        - python
        - cupy-cuda12x  # [not osx]
    test:
      imports:
        - ray.dag                                     # [not (osx and arm64)]

  - name: ray-air
    build:
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-data', exact=True) }}
        - {{ pin_subpackage('ray-serve', exact=True) }}
        - {{ pin_subpackage('ray-train', exact=True) }}
        - {{ pin_subpackage('ray-tune', exact=True) }}
    test:
      imports:
        - ray.air                                 # [not (osx and arm64)]

  - name: ray-observability
    build:
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('ray-default', exact=True) }}
        - opentelemetry-api
        - opentelemetry-sdk
        - opentelemetry-exporter-otlp
    test:
      commands:
        - echo "no tests for ray-observability, it is a convenience bundle"

about:
  home: https://www.ray.io/
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - licenses/abseil-LICENSE.txt
    - licenses/antirez-redis-COPYING.txt
    - licenses/arrow-LICENSE.txt
    - licenses/boost-LICENSE_1_0.txt
    - licenses/boringssl-LICENSE.txt
    - licenses/deckarep-golang-set-LICENSE.txt
    - licenses/flatbuffers-LICENSE.txt
    - licenses/gabime-spdlog-LICENSE.txt
    - licenses/gflags-COPYING.txt
    - licenses/glog-COPYING.txt
    - licenses/go-logr-LICENSE.txt
    - licenses/googletest-LICENSE.txt
    - licenses/grpc-LICENSE.txt
    - licenses/msgpack-COPYING.txt
    - licenses/onsi-ginkgo-LICENSE.txt
    - licenses/onsi-gomega-LICENSE.txt
    - licenses/opencensus-LICENSE.txt
    - licenses/opencensus-proto-LICENSE.txt
    - licenses/prometheus-LICENSE.txt
    - licenses/redis-hiredis-COPYING.txt
    - licenses/tporadowski-redis-license.txt
    - licenses/zlib-LICENSE.txt
  summary: Ray is a fast and simple framework for building and running distributed applications.
  description: |
    Ray is a fast and simple framework for building and running
    distributed applications. It is split into ray-core, ray-default,
    ray-dashboard, ray-serve, ray-rllib, ray-client, ray-data, ray-tune,
    ray-train, ray-air, ray-observability and ray-all packages.
  doc_url: https://docs.ray.io/en/latest/
  dev_url: https://github.com/ray-project/ray

extra:
  recipe-maintainers:
    - dHannasch
    - h-vetinari
    - vnlitvinov
    - krfricke
